// 1. Crear/Usar la base de datos
use("Biblioteca_Digital");

// Creación de la colección autores.

db.createCollection("Autores", {
    validator: {
        $jsonSchema: {
            bsonType: "object",
            required: ["codigo_autor", "nombre", "apellido", "nacionalidad", "fecha_nacimiento", "estado"],
            properties: {
                codigo_autor: {
                    bsonType: "string",
                    pattern: "^AUT[0-9]{4}$"
                },
                nombre: {
                    bsonType: "string",
                    minLength: 1,
                    maxLength: 60
                },
                apellido: {
                    bsonType: "string",
                    minLength: 1,
                    maxLength: 60
                },
                nacionalidad: {
                    bsonType: "string",
                    minLength: 1,
                    maxLength: 60
                },
                fecha_nacimiento: {
                    bsonType: "date"
                },
                estado: {
                    bsonType: "string",
                    enum: ["Inactivo", "Activo"]
                }
            }
        }
    }
});

// Inserción de datos.

use("Biblioteca_Digital");
db.Autores.insertMany([
  {
    codigo_autor: "AUT0001",
    nombre: "Laura",
    apellido: "Esquivel",
    nacionalidad: "Mexicana",
    fecha_nacimiento: new Date("1950-09-30"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0002",
    nombre: "Emma",
    apellido: "Dolujanoff",
    nacionalidad: "Mexicana",
    fecha_nacimiento: new Date("1922-12-08"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0003",
    nombre: "Agustín",
    apellido: "Yáñez",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1904-05-04"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0004",
    nombre: "Ignacio Manuel",
    apellido: "Altamirano",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1834-11-13"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0005",
    nombre: "Rudolfo",
    apellido: "Anaya",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1937-10-30"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0006",
    nombre: "Carlos",
    apellido: "Fuentes",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1928-01-11"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0007",
    nombre: "Carlos Cuauhtémoc",
    apellido: "Sánchez",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1964-04-15"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0008",
    nombre: "Santiago",
    apellido: "Genovés",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1923-12-31"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0009",
    nombre: "Salvador",
    apellido: "Reyes Nevares",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1924-11-21"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0010",
    nombre: "Martín Luis",
    apellido: "Guzmán",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1887-10-06"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0011",
    nombre: "Artemio de Valle",
    apellido: "Arizpe",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1888-01-25"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0012",
    nombre: "José Joaquín",
    apellido: "Fernández de Lizardi",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1776-10-15"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0013",
    nombre: "Vicente",
    apellido: "Leñero",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1933-06-09"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0014",
    nombre: "Mariano",
    apellido: "Azuela",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1873-01-01"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0015",
    nombre: "Manou",
    apellido: "Dornbierer",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1936-12-10"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0016",
    nombre: "Luis",
    apellido: "Spota",
    nacionalidad: "Mexicano",
    fecha_nacimiento: new Date("1925-06-13"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0017",
    nombre: "General Francisco",
    apellido: "Morazán",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1792-10-03"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0018",
    nombre: "Francisco",
    apellido: "Gavidia",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1863-12-29"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0019",
    nombre: "Arturo",
    apellido: "Ambrogi",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1863-12-29"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0020",
    nombre: "Aloberto",
    apellido: "Masferrer",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1868-07-24"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0021",
    nombre: "Alberto",
    apellido: "Rivas Bonilla",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1891-09-04"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0022",
    nombre: "Serafin",
    apellido: "Quiteño",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1906-09-16"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0023",
    nombre: "Raul",
    apellido: "Contreras",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1896-04-03"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0024",
    nombre: "Ricardo",
    apellido: "Triagueros de León",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1896-04-03"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0025",
    nombre: "Jose Maria",
    apellido: "Peralta Lagos",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1873-07-25"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0026",
    nombre: "Vicente",
    apellido: "Rosales y Rosales",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1894-11-06"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0027",
    nombre: "Juan José",
    apellido: "Cañas",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1826-01-19"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0028",
    nombre: "Salvador",
    apellido: "Salazar Arrué",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1899-10-22"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0029",
    nombre: "Miguel Ángel",
    apellido: "Espino",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1902-12-17"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0030",
    nombre: "Horacio",
    apellido: "Castellanos Moya",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1957-11-21"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0031",
    nombre: "Jacinta",
    apellido: "Escudos",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1961-09-01"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0032",
    nombre: "Manlio",
    apellido: "Argueta",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1935-12-24"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0033",
    nombre: "David",
    apellido: "Escobar Galindo",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1943-10-04"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0034",
    nombre: "José",
    apellido: "Rutilio Quezada",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1930-09-30"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0035",
    nombre: "Carlos",
    apellido: "Anchetta",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1936-12-10"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0036",
    nombre: "Alvaro",
    apellido: "Menen Desleal",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1931-03-13"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0037",
    nombre: "Alfonso",
    apellido: "Quijada Urías",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1940-12-08"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0038",
    nombre: "Mario",
    apellido: "Bencastro",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1949-03-20"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0039",
    nombre: "Alvaro",
    apellido: "Dario Lara",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1966-03-03"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0040",
    nombre: "Rafael",
    apellido: "Mendoza",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1943-02-02"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0041",
    nombre: "Ricardo",
    apellido: "Lindo",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1947-02-05"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0042",
    nombre: "Joaquín",
    apellido: "Meza",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1980-03-24"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0043",
    nombre: "Roberto",
    apellido: "Castillo",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1950-01-01"),
    estado: "Activo"
  },
  {
    codigo_autor: "AUT0044",
    nombre: "Carmen",
    apellido: "González Huguet",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1958-11-15"),
    estado: "Activo"
  },
  {
    codigo_autor: "AUT0045",
    nombre: "Carlos",
    apellido: "Balmore Fuentes",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1955-12-29"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0046",
    nombre: "Luis Armando",
    apellido: "González",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1961-04-26"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0047",
    nombre: "Marvin",
    apellido: "Galeas",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1956-06-12"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0048",
    nombre: "Roque",
    apellido: "Dalton",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1935-04-14"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0049",
    nombre: "Claudia",
    apellido: "Lars",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1899-12-20"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0050",
    nombre: "Alfredo",
    apellido: "Espino",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1900-01-08"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0051",
    nombre: "Oswaldo",
    apellido: "Escobar Velado",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1919-10-11"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0052",
    nombre: "Pedro",
    apellido: "Geoffroy Rivas",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1908-09-16"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0053",
    nombre: "Matilde Elena",
    apellido: "López",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1920-02-20"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0054",
    nombre: "Roberto",
    apellido: "Armijo",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1937-12-13"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0055",
    nombre: "Mercedes",
    apellido: "Duran",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1933-09-09"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0056",
    nombre: "Italo",
    apellido: "López Vallecillos",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1932-11-15"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0057",
    nombre: "Jorge",
    apellido: "Galan",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1973-01-01"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0058",
    nombre: "Maura",
    apellido: "Echeverría",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1935-05-03"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0059",
    nombre: "Krisma",
    apellido: "Mancia",
    nacionalidad: "Salvadoreña",
    fecha_nacimiento: new Date("1980-02-13"),
    estado: "Activo",
  },
  {
    codigo_autor: "AUT0060",
    nombre: "Luis",
    apellido: "Alvarengua",
    nacionalidad: "Salvadoreño",
    fecha_nacimiento: new Date("1940-01-01"),
    estado: "Activo",
  },
]
)
