// 1. Crear/Usar la base de datos
use("Biblioteca_Digital");

// Creación de la colección autores.

db.createCollection("Autores", {
    validator: {
        $jsonSchema: {
            bsonType: "object",
            required: ["codigo_autor", "nombre", "apellido", "nacionalidad", "fecha_nacimiento", "estado"],
            properties: {
                codigo_autor: { 
                    bsonType: "string", 
                    pattern: "^AUT-[0-9]{4}$" 
                },
                nombre: { 
                    bsonType: "string", 
                    minLength: 1, 
                    maxLength: 60 
                },
                apellido: { 
                    bsonType: "string", 
                    minLength: 1, 
                    maxLength: 60 
                },
                nacionalidad: { 
                    bsonType: "string", 
                    minLength: 1, 
                    maxLength: 60 
                },
                fecha_nacimiento: { 
                    bsonType: "date" 
                },
                estado: { 
                    bsonType: "string", 
                    enum: ["Inactivo", "Activo"] 
                }
            }
        }
    }
});

// Inserción de datos.

use("Biblioteca_Digital");
db.Autores.insertMany([
  {
    codigo_autor:AUT0001,
    nombre:"Laura",
    apellido:"Esquivel",
    nacionalidad:"Mexicana",
    fecha_nacimiento:"30-09-1950",
    estado:"Activo",
  },
  {
    codigo_autor:AUT0002,
    nombre:"Emma",
    apellido:"Dolujanoff",
    nacionalidad:"Mexicana",
    fecha_nacimiento:"08-12-1922",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0003,
    nombre:"Agustín",
    apellido:"Yáñez",
    nacionalidad:"Mexicano",
    fecha_nacimiento:"04-05-1904",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0004,
    nombre:"Ignacio Manuel",
    apellido:"Altamirano",
    nacionalidad:"mexicano",
    fecha_nacimiento:"13-11-1834",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0005,
    nombre:"Rudolfo",
    apellido:"Anaya",
    nacionalidad:"mexicano",
    fecha_nacimiento:"30-10-1937",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0006,
    nombre:"Carlos",
    apellido:"Fuentes",
    nacionalidad:"mexicano",
    fecha_nacimiento:"11-11-1928",
    estado:"Activo",
    },
        {
    codigo_autor:AUT0007,
    nombre:"Carlos Cuauhtémoc",
    apellido:"Sánchez",
    nacionalidad:"mexicano",
    fecha_nacimiento:"15-04-1964",
    estado:"Activo",
    },
        {
    codigo_autor:AUT0008,
    nombre:"Santiago",
    apellido:"Genovés",
    nacionalidad:"mexicano",
    fecha_nacimiento:"31-12-1923",
    estado:"Activo",
    },
        {
    codigo_autor:AUT0009,
    nombre:"Salvador",
    apellido:"Reyes Nevares",
    nacionalidad:"mexicano",
    fecha_nacimiento:"21-11-1924",
    estado:"",
    },
        {
    codigo_autor:AUT0010,
    nombre:"Martín Luis",
    apellido:"Guzmán",
    nacionalidad:"mexicano",
    fecha_nacimiento:"06-10-1887",
    estado:"Activo",
    },
        {
    codigo_autor:AUT0011,
    nombre:"Artemio de Valle",
    apellido:"Arizpe",
    nacionalidad:"mexicano",
    fecha_nacimiento:"25-01-1888",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0012,
    nombre:"José Joaquín",
    apellido:"Fernández de Lizardi",
    nacionalidad:"mexicano",
    fecha_nacimiento:"15-10-1776",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0013,
    nombre:"Vicente",
    apellido:"Leñero",
    nacionalidad:"mexicano",
    fecha_nacimiento:"09-06-1933",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0014,
    nombre:"Mariano",
    apellido:"Azuela",
    nacionalidad:"mexicano",
    fecha_nacimiento:"01-01-1873",
    estado:"Activo",
    },
    {
    codigo_autor:AUT0015,
    nombre:"Manou",
    apellido:"Dornbierer",
    nacionalidad:"mexicana",
    fecha_nacimiento:"10-12-1936",
    estado:"",
    },
    {
    codigo_autor:AUT0016,
    nombre:"Luis",
    apellido:"Spota",
    nacionalidad:"mexicano",
    fecha_nacimiento:"13-06-1925",
    estado:"Activo",
        },
    {
    codigo_autor:AUT0017,
    nombre:"Manou",
    apellido:"Dornbierer",
    nacionalidad:"mexicana",
    fecha_nacimiento:"10-12-1936",
    estado:"",
    },
        
    {
    codigo_autor:AUT0018,
    nombre:"Miguel",
    apellido:" Álvarez Castro",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"29-09-1795",
    estado:"Activo",
    },
        
    {
    codigo_autor:AUT0019,
    nombre:"Francisco",
    apellido:"Gavidia",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"29-12-1863",
    estado:"",
    },
        
    {
    codigo_autor:AUT0020,
    nombre:"Arturo",
    apellido:"Ambrogi",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"19-10-1875",
    estado:"Activo",
    },
        
    {
    codigo_autor:AUT0021,
    nombre:"Alberto",
    apellido:"Masferrer",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"24-07-1868",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0022,
    nombre:"Alberto",
    apellido:"Rivas Bonilla",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"04-09-1891",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0023,
    nombre:"Serafin",
    apellido:"Quiteño",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"16-09-1906",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0024,
    nombre:"Raul",
    apellido:"Contreras",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"03-04-1896",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0025,
    nombre:"Ricardo",
    apellido:"Triagueros de León",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"13-11-1917",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0026,
    nombre:"Jose Maria",
    apellido:"Peralta Lagos",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"25-07-1873",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0027,
    nombre:"Vicente",
    apellido:"Rosales y Rosales",
    nacionalidad:"Salavadoreño",
    fecha_nacimiento:"06-11-1894",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0028,
    nombre:"Juan José",
    apellido:"Cañas",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"19-01-1826",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0029,
    nombre:"Salvador",
    apellido:"Salazar Arrué",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"22-10-1899",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0030,
    nombre:"Miguel Ángel",
    apellido:"Espino",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"17-12-1902",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0031,
    nombre:"Horacio",
    apellido:"Castellanos Moya",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"21-11-1857",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0032,
    nombre:"Jacinta",
    apellido:"Escudos",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"01-09-1861",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0033,
    nombre:"Manlio",
    apellido:"Argueta",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"24-12-1935",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0034,
    nombre:"David",
    apellido:"Escobar Galindo",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"04-10-1943",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0035,
    nombre:"José",
    apellido:"Rutilio Quezada",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"30-09-1930",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0036,
    nombre:"Carlos",
    apellido:"Anchetta",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"10-12-1936",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0037,
    nombre:"Alvaro",
    apellido:"Menen Desleal",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"13-03-1931",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0038,
    nombre:"Alfonso",
    apellido:"Quijada Urías",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"08-12-1940",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0039,
    nombre:"Mario",
    apellido:"Bencastro",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"20-03-1949",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0040,
    nombre:"Alvaro",
    apellido:"Dario Lara",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"03-03-1966",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0041,
    nombre:"Rafael",
    apellido:"Mendoza",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"02-02-1943",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0042,
    nombre:"Ricardo",
    apellido:"Lindo",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"05-02-1947",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0043,
    nombre:"Joaquín",
    apellido:"Meza",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"24-03-1980",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0044,
    nombre:"Roberto",
    apellido:"Castillo",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"1950",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0045,
    nombre:"Carmen",
    apellido:"González Huguet",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"15-11-1958",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0046,
    nombre:"Carlos",
    apellido:"Balmore Fuentes",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"29-12-1955",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0047,
    nombre:"Luis Armando",
    apellido:"González",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"26-04-1961",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0048,
    nombre:"Marvin",
    apellido:"Galeas",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"12-06-1956",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0049,
    nombre:"Roque",
    apellido:"Dalton",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"14-04-1935",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0050,
    nombre:"Claudia",
    apellido:"Lars",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"20-12-1899",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0051,
    nombre:"Alfredo",
    apellido:"Espino",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"08-01-1900",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0052,
    nombre:"Oswaldo",
    apellido:"Escobar Velado",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"11-10-1919",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0053,
    nombre:"Pedro",
    apellido:"Geoffroy Rivas",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"16-09-1908",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0054,
    nombre:"Matielde Elena",
    apellido:"López",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"20-02-1920",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0055,
    nombre:"Roberto",
    apellido:"Armijo",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"13-12-1937",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0056,
    nombre:"Mercedes",
    apellido:"Duran",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"09-09-1933",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0057,
    nombre:"Italo",
    apellido:"López Vallecillos",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"15-11-1932",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0058,
    nombre:"Jorge",
    apellido:"Galan",
    nacionalidad:"Salvadoreño",
    fecha_nacimiento:"1973",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0059,
    nombre:"Maura",
    apellido:"Echeverría",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"03-05-1935",
    estado:"Activo",
    },
       {
    codigo_autor:AUT0060,
    nombre:"Krisma",
    apellido:"Mancia",
    nacionalidad:"Salvadoreña",
    fecha_nacimiento:"13-02-1980",
    estado:"Activo",
    },


])
